# Generated by Django 4.2.2 on 2023-07-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_auth', '0004_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='short_org_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
