# Generated by Django 4.1.7 on 2023-07-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_org_name', models.CharField(max_length=255)),
                ('full_org_name', models.CharField(max_length=255)),
                ('tournament_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('map', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('task', models.TextField()),
                ('example', models.URLField()),
                ('reglament', models.TextField()),
                ('visual_reglament', models.TextField(blank=True, null=True)),
                ('max_pilots', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='tournaments/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try1', models.CharField(blank=True, max_length=255, null=True)),
                ('try2', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
